name: Android CI

on:
  push:
    branches:
      - main
      - master

  pull_request:

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Grant execute permission
        run: chmod +x build.py

      - name: Build Module
        run: python3 build.py build

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-module
          path: out/*.zip
