name: Build Zygisk Module

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        id: setup_ndk
        with:
          ndk-version: r25c
          link-to-sdk: true

      - name: Build with Build.py
        run: |
          python3 build.py build --ndk "${{ steps.setup_ndk.outputs.ndk-path }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bleach-Damage-Mod
          path: out/*.zip
